services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: jarikita_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: jarikita
      MYSQL_USER: jarikita
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"

volumes:
  mysql_data: